base_config: [
  '../base/context/default_mode.yaml',
  '../base/datasets/finetune_dataset.yaml',
  '../base/models/swin_base_p4_w7.yaml',
  '../base/schedules/default_schedule.yaml',
  '../base/runner/runner.yaml',
  '../base/modelarts/aicc.yaml',
  '../base/__base__.yaml']

arch: "simmim"
use_parallel: True
profile: False
auto_tune: True  # dataset performance
filepath_prefix: "./autotune"
autotune_per_step: 10

model:
  patch_type: 'pi_conv'
  use_lbp: False

finetune_dataset:
  train_path: "/home/linbert/work/chinakevin/pretrain_chinakevin/Dataset/NWPU_RESISC45/train"
  eval_path: "/home/linbert/work/chinakevin/pretrain_chinakevin/Dataset/NWPU_RESISC45/val"
  eval_interval: 1
  eval_offset: -1
  input_columns: [ "image", "label" ]
  output_columns: [ "image", "label" ]
  column_order: [ "image", "label" ]
  samples_num: 25200 # 50000 for imagenet, 25200 for nwpu， 5000 for aid_test.

train_config:
  epoch: 200
  batch_size: 32
  image_size: 224
  per_epoch_size: 0
  num_classes: 46
  resume_ckpt: "/home/linbert/work/chinakevin/ringmo_swin/ring-mo_rank_0-189_976.ckpt"

loss_type: "soft_ce"

# optimizer
optimizer:
  optim_name: "AdamW"
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001 # 1e-8
  weight_decay: 0.05
  layer_decay: 0.65

# lr sechdule
lr_schedule:
  lr_type: "warmup_cosine_decay_simmim"
  base_lr: 0.00125
  min_lr: 0.00000025
  warmup_lr: 0.00000025
  warmup_epochs: 20

aicc_config:
  obs_path: "Input your obs path if code is running on modelarts else invalid."
  upload_frequence: 1
  keep_last: False
