model:
    backbone: 'vit'
    patch_size: 16
    in_chans: 3
    embed_dim: 1024
    depth: 24
    num_heads: 16
    mlp_ratio: 4
    drop_rate: 0.
    drop_path_rate: 0.2
    init_values: 0.1
    use_abs_pos_emb: False
    use_rel_pos_bias: True  # if set window size, it's True
    use_shared_rel_pos_bias: False  # if set window size, it's True
    use_mean_pooling: True