# optimizer
optimizer:
    optim_name: "AdamW"
    beta1: 0.9
    beta2: 0.999
    eps: 0.00000001 # 1e-8
    weight_decay: 0.05

# lr sechdule
lr_schedule:
    lr_type: "warmup_cosine_decay"
    base_lr: 0.00015
    min_lr: 0.
    warmup_lr: 0.
    warmup_epochs: 40
